<?php

class UserSession {
    private $id;                        // Unique ID for session (db only)
    private $userId;                    // User the session belongs to
    private $startTime;                 // Time session started
    private $endTime;                   // Time session started
    private $lastActivity;              // Last time user did anything
    private $sessionTimeout;            // Time until session expires
    private $phpSessionId;              // Session ID generated by PHP
    private $phpSessionIdCreated;       // Time that session id was generated
    private $phpSessionIdTimeout;       // Time until key needs changed.
    private $rememberMe;                // Timeout / Don't Timeout
    private $rememberMeTimeout;         // Max length a rememberMe will last.
    private $valid;                     // Is session still active
}

?>